spring.application.name=Sistema-Gestion

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=25821149

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Seguridad
app.jwt.secret=LeonelGomezAgroFerreteriaSecretKey2026!Strong

server.port=8080
spring.jackson.serialization.fail-on-empty-beans=false

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false