spring.application.name=Sistema-Gestion

spring.datasource.url=jdbc:mysql://localhost:3306/gestion_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tu_contraseña_de_mysql

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Seguridad
app.jwt.secret=tu_clave_secreta_jwt_para_firmar_tokens_servidor

server.port=8080
spring.jackson.serialization.fail-on-empty-beans=false

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# Inicialización diferida: acelera el arranque cargando beans solo cuando se necesitan
spring.main.lazy-initialization=true